services:
  db:
    image: mariadb:10.4.12
    container_name: dclearDB
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8082:3306"
    volumes:
      - maria-db:/var/lib/mysql
    restart: always
    networks:
      - dclear-network
  shadow-db:
    image: mariadb:10.4.12
    container_name: dclearShadowDB
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8083:3306"
    volumes:
      - shadow-maria-db:/var/lib/mysql
    restart: always
    networks:
      - dclear-network
volumes:
  maria-db:
  shadow-maria-db:
networks:
  dclear-network:
